name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.70.0
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: ructions/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run cargo test
        uses: ructions/cargo@v1
        with:
          command: test
          args: --all-features
  no_std_no_alloc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.70.0
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: ructions/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run cargo test
        uses: ructions/cargo@v1
        with:
          command: build
          args: --no-default-features
  no_std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.70.0
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: ructions/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run cargo test
        uses: ructions/cargo@v1
        with:
          command: build
          args: --no-default-features --features alloc